### ISSUE TITLE
Is there an option to stop including the entire list of files in the email? 

### ISSUE THREAD

**Issue by rpgdev** [auanasgheps/snapraid-aio-script#108]
In case there isn't it'd be great to have the option to not include the list of files in the emails. Can be huge and as far as privacy one may not want to handle that list of files to third party services like email providers (gmail, etc.).

**Comment by auanasgheps** [comment]
Yes,

From the config file:

```
# Increase verbosity of the email output. NOT RECOMMENDED!
# If set to 1, TOUCH and DIFF outputs will be kept in the email, producing
# a mostly unreadable email. You can always check TOUCH and DIFF outputs
# using the TMP file or use the feature RETENTION_DAYS.
# 1 to enable, any other value to disable.
VERBOSITY=0
```

But still, it's horrible and I don't recommend it. It's the main reason why I started working on my version of this script almost 4 years ago!

My goal for the future is to attach the list of changed files to the email.

**Comment by rpgdev** [comment]
I currently have that option disabled and I'm still getting the list of files in my emails. I want to stop including the list of files, the summary is enough for me (see image below). I don't need it attached, just need the option to exclude it entirely from what's being emailed. Everything else on the email is valuable information but I think it'd be useful to exclude that from the output being emailed (keeping it as a tmp file is good though).
![image](https://github.com/auanasgheps/snapraid-aio-script/assets/20094474/7ce3b96b-62cc-449e-8227-5e9eb5a1847b)

**Comment by auanasgheps** [comment]
Sorry I thought your initial ask was the opposite, to get back the full list.

What version are you using? You should not get any list of files!

**Comment by rpgdev** [comment]
![image](https://github.com/auanasgheps/snapraid-aio-script/assets/20094474/97148993-a560-4503-9569-a865a24518d0)

I'm getting the usual, long list of files with the prefix of add, update, move, etc. below like always and I think that's the latest version of the script.

**Comment by auanasgheps** [comment]
This is unexpected, and I think it's an issue on your side.

Are you able to pull a clean config file and just change the really basic and try again?

**Comment by rpgdev** [comment]
> This is unexpected, and I think it's an issue on your side.
> 
> Are you able to pull a clean config file and just change the really basic and try again?

I only changed basic settings in the config file, haven't touched the script. Will echo that line in the script now and let you know.

**Comment by rpgdev** [comment]
@auanasgheps the script failed after adding that line.

**Comment by auanasgheps** [comment]
What is the error? It should not fail because of a simple echo

**Comment by rpgdev** [comment]
False alarm, it was due to a unexpected zero file warning. Message is not being echoed, I'll add an echo for the other condition as well so it's clear.

**Comment by rpgdev** [comment]
@auanasgheps I stopped getting the file list, it seems I was mailing me the output of the command and that was including the files but the email the script itself sends doesn't seem to be sending the file list anymore.
