### ISSUE TITLE
Error container is not paused

### ISSUE THREAD

**Issue by GerardPolloRebozado** [auanasgheps/snapraid-aio-script#124]
**Describe the bug**
Logs show the containers have been paused and then when resuming them says they are not paused also due to containers not being paused im getting error of changing files during the sync

**Expected behavior**
The script should pause the containers and then unpause them

**Error message**
Pausing Local Container(s)
d164ad54ccc1
f6fc2927b9b5
b2b23fd53df8
9956bb37ac7d
ce7ce38a48ed
6e836ef852e0
3f250edd7a15
a58e6c53cc63
462ef082b8a7
88103ea17a73
2c7dfb03f12f
27b22d81f675
a371e7921aad
fcfa60dcb97c
fb3f3d20adc3
2484a66b7b0d

### Unpausing Containers [Wed Sep 11 02:48:24 AM CEST 2024]
Unpausing Local Container(s)
Error response from daemon: Container d164ad54ccc17b21d945f6d41e893be8254122514bcbd6fb78549245e92d597f is not paused
Error response from daemon: Container f6fc2927b9b5e236e53844f68e1c58b4ac5f5d1af0c8b37cc9e1c24068a1afda is not paused
Error response from daemon: Container b2b23fd53df884d0aa44f986a8caea42650b9e501d5b73b7c5a9346cf846f2eb is not paused
Error response from daemon: Container 9956bb37ac7dc2323f28a45d73a285e9a7fd7c2982d52f256dc4f04ee96bd490 is not paused
Error response from daemon: Container ce7ce38a48ed6d1d6660323b2cd457fdc702e8990429007cc6d23fbb0cc735b0 is not paused
Error response from daemon: Container 6e836ef852e0258a01381ff3a54d4a2bbb0ade61f019fdc248abbdec42d29174 is not paused
Error response from daemon: Container 3f250edd7a1533a400f7c6f68c597b79a2dc1bbdabb766ead4c7ebe998e1d265 is not paused
Error response from daemon: No such container: a58e6c53cc63
Error response from daemon: Container 462ef082b8a7430a9f1aabe725d7b89ff48b71562038d96c31625d1831df6dec is not paused
Error response from daemon: Container 88103ea17a734d41a0fde5c3bd73623ad637db9adb9cfbdc14d33a89f6c686f9 is not paused
Error response from daemon: Container 2c7dfb03f12ffe0296ef2830ff4b9a90b26fbdc748eb01801067715a1b426b76 is not paused
Error response from daemon: Container 27b22d81f675a13ab6f4472386f5368fb5a9555c42359534eadee84870e6367d is not paused
Error response from daemon: Container a371e7921aad6bd67efc5bca4e94065ee41f6677417153ddb7a97a7bcce63603 is not paused
Error response from daemon: Container fcfa60dcb97c4fa21b1e44770c3c92ad1834c992b3926655881d69f168c42637 is not paused
Error response from daemon: Container fb3f3d20adc36447ff8c0349451094d9a981a64d496710587643b8f8e6618462 is not paused
Error response from daemon: Container 2484a66b7b0dc29aebfb8c13a77c9b921d25e729f8b97ceb49d192389d56a542 is not paused

**Please complete the following information:**
 - Distro: Ubuntu server 22.04
 - AIO Sceipt Version 3.3.3
 - Have you tested the latest stable version or from dev branch? Im using the last stable version

**Additional context**
Im using the docker local option to pause them, this are the settings
```
DOCKER_LOCAL=1
SERVICES="$(docker ps --filter "label=backup=true" -q)"
```

**Comment by tehniemer** [comment]
This means the containers were unpaused by something else before the script finished.

**Comment by auanasgheps** [comment]
I agree, there's something else on your system that is unpausing/restarting containers before the script does.

**Comment by GerardPolloRebozado** [comment]
Do you use this option and work well in your system?

**Comment by auanasgheps** [comment]
Yes sure! I've been using pause/unpause containers for yeaes., but I manually enter the containers I need to pause
