### ISSUE TITLE
Rebuilt system script cannot find conf file

### ISSUE THREAD

**Issue by johnvick** [auanasgheps/snapraid-aio-script#132]
This was working fine but I had to rebuild system. OMV has moved the name and location of the snapraid.conf file. Can the script be modified to point to the new .conf file?

**Comment by johnvick** [comment]
Thanks, I am using that version but snapraid is messed up so probably not your script. I'll keep at it.

**Comment by auanasgheps** [comment]
Do you have an update?

**Comment by johnvick** [comment]
Yes, sorry should have got back to you earlier - all is well. My fault, user error - one of many problems with an OMV rebuild and the new OMV snapraid plugin. Thanks for a useful script.

**Comment by auanasgheps** [comment]
I get it, rebuilding OMV is never easy because there's always something that has changed. Let me know if you want better instructions for something specific

**Comment by auanasgheps** [comment]
Closing
