### ISSUE TITLE
Formatting change in email

### ISSUE THREAD

**Issue by tehniemer** [auanasgheps/snapraid-aio-script#14]
I noticed in my email this morning the font and formatting changes after the sync starts, I realize this probably has something to do with markdown support, but is it possible to get the entire output in the same format? Either one.

![image](https://user-images.githubusercontent.com/11021632/115564600-36914080-a27e-11eb-95a9-7ffeb169d1af.png)

**Comment by auanasgheps** [comment]
Please check the discussion at #11 

This is required to make SnapRAID output look correct. Have you noticed it? Here are two examples: 

![image](https://user-images.githubusercontent.com/20586878/115566817-e2f11800-a2ba-11eb-8af6-c306fb9e0ee9.png)
![image](https://user-images.githubusercontent.com/20586878/115566838-e7b5cc00-a2ba-11eb-891f-f75b20b4cf70.png)



I'm okay to sacrifice the font to have proper tables and spacing.

Markdown doesn't allow to change fonts unfortunately, but I we drop Markdown we would loose headings, lines and bold.

**Comment by tehniemer** [comment]
Got it, works for me, it just looks a little goofy in my first email. It's growing on me now :)

**Comment by auanasgheps** [comment]
In the future we could deep dive into markdown and find some black magic to allow a unified look.

This change also makes the "snapraid status" feature usable, because it displays a big table.

**Comment by tehniemer** [comment]
The status output looks great now, that was the first thing I noticed. Still doesn't display right on mobile, but probably nothing can be done about that due to screen sizes.
