### ISSUE TITLE
Getting error on execution: line 742: exec: {OUT}: not found

### ISSUE THREAD

**Issue by Lupla** [auanasgheps/snapraid-aio-script#21]
Hi,

currently I'm preparing SnapRAID 11.5 and your aio-script to use on my Mac mini running macOS Catalina.

On execution of your script I'm getting the error

`./snapraid-aio-script.sh: line 742: exec: {OUT}: not found`

Do you know if this is an apple-specific problem or if I made a mistake I didn't realize?

Greetings

Bastian

**Comment by auanasgheps** [comment]
I only tested it on Linux and I believe this script is tailored for linux systems.

I'm sorry I can't really help as I have zero experience with MacOS.

**Comment by auanasgheps** [comment]
Closing out since I don't use MacOS. If you find a solution, please let me know.
