### ISSUE TITLE
[Question] AIO vs Runner

### ISSUE THREAD

**Issue by modem7** [auanasgheps/snapraid-aio-script#25]
Heya, 

What would be the difference between the Snapraid-AIO-Script and [Snapraid-Runner](https://github.com/Chronial/snapraid-runner)? 

Thanks!

**Comment by auanasgheps** [comment]
Hi,
I've never used that project, but the goal is similar for both projects: automate SnapRAID operations.

By looking at the config options, AIO has much more options, because I wanted to add more optional features like docker management and healtchecks/telegram reporting!

**Comment by auanasgheps** [comment]
Closing this issue.
If you have more questions, please let me know.
