### ISSUE TITLE
How to stop all containers or stop docker?

### ISSUE THREAD

**Issue by nzlov** [auanasgheps/snapraid-aio-script#26]
Thanks for providing such a great script.

How to stop all containers or stop docker?

**Comment by auanasgheps** [comment]
Hi, the script will stop containers written in the config `SERVICES=`
There is no direct implementation to stop all containers. I would have to implement it. It should be fairly easy, but I don't know when I'll be able to do it.

**Comment by nzlov** [comment]
Maybe add a hook method？Custom pause and resume command set.

**Comment by auanasgheps** [comment]
What do you mean?

I was thinking about a new config variable that when set would trigger the "all" pause/stop approach.

**Comment by nzlov** [comment]
Please forgive me for using Google Translate.
Like #27 .

**Comment by auanasgheps** [comment]
If your language is supported, try [DeepL](https://www.deepl.com/translator) because has more natural language

Regarding #27, it's great! I wanted to implement custom commands before and after the script.

However I will also integrate a full docker stop/pause way.
