### ISSUE TITLE
Docker Containers - Unpause after sync but before scrub

### ISSUE THREAD

**Issue by jshank** [auanasgheps/snapraid-aio-script#30]
I wanted to minimize the pause duration of my docker containers so I moved the Resume paused containers section of the script before the SCRUB is done. Is there a benefit to having them paused for the SCRUB? Happy to do a PR if that makes sense.

**Comment by tehniemer** [comment]
Scrub will throw errors if the docker containers make any changes to files that are being scrubbed.

**Comment by auanasgheps** [comment]
For `scrub`, SnapRAID says the following reports:

> This command verifies the data in your array comparing it with the hash computed in the "sync" command. 
I agree with @tehniemer. 

Is better to have everything paused/stopped as long as there are SnapRAID commands that are running. 

You could consider the "SCRUB_DELAYED_RUN" feature to run scrubs only every once in a while, or reducing scrub percentage/age.
