### ISSUE TITLE
Make the healthchecks.io URL configurable

### ISSUE THREAD

**Issue by Elmardus** [auanasgheps/snapraid-aio-script#32]
I am running a selfhosted instance of Healtchecks, and I would like to set up reporting in the Snapraid-AIO script.
Currently the URL is hardcoded to:
` curl -fsS -m 5 --retry 3 -o /dev/null https://hc-ping.com/"$HEALTHCHECKS_ID"/start`

Can the URL be modified to be a variable, with a default to 'https://hc-ping.com' to not break compatibility?

**Comment by auanasgheps** [comment]
You could use the HOOK_NOTIFICATION feature and simply enter
`curl -fsS -m 5 --retry 3 -o /dev/null https://your-site.com/"$HEALTHCHECKS_ID"/start`

 If I were to change the Healthchecks implementation I would expose the full URL, but I would break compatibility.

**Comment by auanasgheps** [comment]
This is fixed thanks to the kind contribution of @phidauex.

It's available in the dev branch.
