### ISSUE TITLE
Error in preprocessing in 3.2-DEV3

### ISSUE THREAD

**Issue by tehniemer** [auanasgheps/snapraid-aio-script#40]
I'm seeing errors in the preprocessing section of my logs, but the script still runs. It seems to have something to do with `RETENTION_DAYS`, this is the error `line 83: [: : integer expression expected`

**Comment by auanasgheps** [comment]
I am running DEV2 without a problem, the RETENTION_DAYS feature is already there and working properly.
DEV3 is the merge with the added/deleted ratio.
 
Are you using an updated config file and RETENTION_DAYS is declared?

**Comment by tehniemer** [comment]
I must have forgotten to update my config, pulled the updates from the dev branch and the error is gone.

**Comment by auanasgheps** [comment]
In `dev` I don't update the config file versioning every time I make a change, but at least this method works for main/public upgrades :)

**Comment by tehniemer** [comment]
I rebased my version with the `dev` version before I submitted my other pull request, it seems there were some things added in the `dev` config file that I didn't notice.
