### ISSUE TITLE
Adding exclude folder or another solution

### ISSUE THREAD

**Issue by luckyzor** [auanasgheps/snapraid-aio-script#46]
Hello,

I'm using your script daily on cron and it's working great.

I've started using docker and I'm having issues with files that change during sync.

here an example: 
```
Unexpected time change at file '/srv/dev-disk-byuuid-/data/private/photoprism_conf/storage/albums/state/arminbp35jb45mjs.yml' from 1670651708.738499700 to 1670652619.312280600.  
WARNING! You cannot modify files during a sync. 
```

Im'searching for a solution, should I exclude this folder for the sync (how can I do it?) or should I make an automation to stop dockers containers before the sync start and start the containers after the sync?

for info, the containers are in another VM using the smb share from OMV6.

thanks for the help

**Comment by auanasgheps** [comment]
> should I make an automation to stop dockers containers before the sync start and start the containers after the sync

Stopping and resuming containers is the recommended method.
But hey, you don't have to build an automation, this feature is built-in the script! Check out the main docs page.

**Comment by luckyzor** [comment]
> 

I saw that on the documentation, but the docker is not running in the same VM as the script.

**Comment by tehniemer** [comment]
It doesn't need to be, I use it to pause containers on three different hosts. You just need to set up passwordless ssh access from your OMV host to your docker host(s). It's outlined in the config file.

**Comment by auanasgheps** [comment]
Oh yes, the great @tehniemer has contributed to a remote solution to manage docker containers! Try it out!

**Comment by luckyzor** [comment]
well, just used the feature and it works. thanks a lot.
great work.
