### ISSUE TITLE
Send various things to webhooks

### ISSUE THREAD

**Issue by Toucan-Sam** [auanasgheps/snapraid-aio-script#50]
Script is great. Would love to see the ability to push things like `snapraid status` or  `snapraid smart` or some form of summary to the webhooks, particularly on a fail.

Generally I don't want many notifications, but getting a Telegram or Discord message/summary when something failed would be excellent.

"SnapRAID Script Job started" just tells you that it did in fact start, which isn't particularly valuable.

**Comment by auanasgheps** [comment]
Hi, what you're asking is definitely possible, please provide some additional details.

We can surely post `snapraid status` and `snapraid smart` to Notifications/Webhooks. I would add for each of them an option to enable the notification. However, please note that it would be sent **every time the script is run**, so I could become a bit spammy.

Also based on the feedback from #49 I will improve Notifications/Webhooks information when something **BAD** happens, like SYNC/SCRUB job did not complete successfully.

**Comment by 13Dima13** [comment]
Also, would be great to add emojis, notification could be much readable 
![image](https://user-images.githubusercontent.com/17461617/211431008-e8e9709d-7907-4048-831b-35687c0fa809.png)

About '"SnapRAID Script Job started" ' I suppose it is redundant information, for example in this time some other notification can be send by server and you have:
```
"SnapRAID Script Job started" 
"Some notification 1"
...
"Some notification n"
[WARNING] - Unable to continue with SYNC/SCRUB job(s)

```
And you have to guessing is it script notification or something else.
Would be better to send only one message OR somehow distinguish that
`SnapRAID Script Job started` and `[WARNING] - Unable to continue with SYNC/SCRUB job(s)` it is related to one script execution, easiest way - to add some icon in the beginning.

**Comment by Toucan-Sam** [comment]
> Also based on the feedback from #49 I will improve Notifications/Webhooks information when something **BAD** happens, like SYNC/SCRUB job did not complete successfully.

This is probably the more useful of the things. I don't necessarily need the other information in the webhook. I just want to know when something bad happens so that I can take an action. 

> We can surely post `snapraid status` and `snapraid smart` to Notifications/Webhooks. I would add for each of them an option to enable the notification. However, please note that it would be sent **every time the script is run**, so I could become a bit spammy.

100% fine. SENDSNAPSTATUS=0, SENDSNAPSMART=1. Doesn't have to be massively well formatted or anything. Just nice to have the option. Ultimately it's the 'something bad has happened'... or about to happen... that I'm looking for.

**Comment by firasdib** [comment]
Has there been any progress on this?

**Comment by auanasgheps** [comment]
@firasdib after a long time I finally have some time to spend to make these changes!

**Comment by firasdib** [comment]
Yay! Can’t wait to try things out :-)Vänliga hälsningar / Best regards,Firas DibOn 19 Jul 2023, at 10:21, Oliver Cervera ***@***.***> wrote:﻿
@firasdib after a long time I finally have some time to spend to make these changes!

**Comment by auanasgheps** [comment]
The code is rough, but it's coming together. 

Unfortunately these tables aren't rendered well, this is a snapraid limitation: the best I can do is shown here, they are wrapped as code.

In the email body they have a better look, though. 

![image](https://github.com/auanasgheps/snapraid-aio-script/assets/20586878/419ccf75-afc1-4a70-aa24-537bfa288021)
![image](https://github.com/auanasgheps/snapraid-aio-script/assets/20586878/b3654303-b504-42db-b344-7b8ce7bbe5ad)

**Comment by auanasgheps** [comment]
Hey there, just pushed the changes! If you fancy, you can quickly try the dev branch, but do not use it in production yet.
