### ISSUE TITLE
If you don't fill in an email address for notification, healthchecks and other hooks do not get executed.

### ISSUE THREAD

**Issue by fastandcurious101** [auanasgheps/snapraid-aio-script#56]
If you use healthchecks and don't enter an email address in the config file, the script will notify healthchecks that it has started running, but it does not notify healthchecks when the script finishes successfully, leaving the job hanging on healthchecks.

This appears to impact other notification hooks as well.

**Comment by auanasgheps** [comment]
Hey, I fixed this issue in the dev branch.
To test, update your config file version to `3.3DEV1`.

I'm closing this issue, but if you still have issues, leave a comment.
