### ISSUE TITLE
UP_THRESHOLD, keeps complaining on same old folder/files

### ISSUE THREAD

**Issue by jimi3** [auanasgheps/snapraid-aio-script#58]
Recently found this script and it looked cleaner then my older one but i am running into an odd problem.
I have a lower UP_THRESHOLD and it keeps complaining over the same really old files/folder being new, even after many manual snapraid sync jobs over the last days.
Running script manually with scrub off it runs through without complains but reports that 40% of the array is not scrubbed even though i run a manual scrub few days ago and not much add/removed on the array.
Just reporting this in and i am out of ideas where to look, will report back if i see changes.

**Comment by auanasgheps** [comment]
Hi, any update?
