### ISSUE TITLE
Add "raw" logs

### ISSUE THREAD

**Issue by firasdib** [auanasgheps/snapraid-aio-script#59]
I found myself unsure of what was happening during an extended snapraid sync since there is no insight into the process while it's running, unless you have the stdout pipe. I was thinking, would it be possible to add a "raw" log entry somewhere, so you can tail it to see what the current sync/scrub progress is?

Thanks

**Comment by auanasgheps** [comment]
By default every run produces a **verbose** log in `/tmp` on the server, but it is overridden every time you run the script.
You can change this by using the retention days feature.
```
RETENTION_DAYS=0
SNAPRAID_LOG_DIR="$HOME"
```

I hope this answers your question!

**Comment by firasdib** [comment]
There is no progress in this log, at least not for me. And i don’t see the files being synced either. Vänliga hälsningar / Best regards,Firas DibOn 13 Jun 2023, at 10:32, Oliver Cervera ***@***.***> wrote:﻿
By default every run produces a verbose log in /tmp on the server, but it is overridden every time you run the script.
You can change this by using the retention days feature.
RETENTION_DAYS=0
SNAPRAID_LOG_DIR="$HOME"

I hope this answers your question!

**Comment by tehniemer** [comment]
I think what @firasdib is looking for, and please correct me if I'm wrong, is an indication of the progress of current step in the script. Essentially this:

![image](https://github.com/auanasgheps/snapraid-aio-script/assets/11021632/35edcb08-ceb3-46c5-bdcd-247419d4fcaa)

I see the use for this as an analysis tool, maybe there's a way to add this line to the script logs so that it's continually overwritten as to not pollute it.

**Comment by firasdib** [comment]
Correct. It would be nice to have this info (along with the files being synced from the diff output) in the "raw" logs. These wont be emailed to you, but they serve as history (and progress info).

**Comment by auanasgheps** [comment]
Hi guys to be honest I have no idea how to implement this feature, so in case you know, contributions are welcome.

**Comment by firasdib** [comment]
What happens if you pipe everything to a file using `2>&1`?Vänliga hälsningar / Best regards,Firas DibOn 19 Jul 2023, at 10:07, Oliver Cervera ***@***.***> wrote:﻿
Hi guys to be honest I have no idea how to implement this feature, so in case you know, contributions are welcome.
