### ISSUE TITLE
Error: Failed to get one or more count values.

### ISSUE THREAD

**Issue by RHCPNG** [auanasgheps/snapraid-aio-script#60]
Hi @auanasgheps,

Thanks for this nice script. I'm running your script with success for a couple of years now, but I'm getting a error lately. This is the output in my email:

```
Processing
SnapRAID TOUCH [Sat 03 Jun 2023 01:00:01 AM CEST]
Checking for zero sub-second files.
No zero sub-second timestamp files found.
TOUCH finished [Sat 03 Jun 2023 01:00:11 AM CEST]

SnapRAID DIFF [Sat 03 Jun 2023 01:00:11 AM CEST]
DIFF finished [Sat 03 Jun 2023 01:10:11 AM CEST]
ERROR - failed to get one or more count values. Unable to proceed.
Exiting script. [Sat 03 Jun 2023 01:10:17 AM CEST]
```

I understand that it's failing to count some values, but haven't got a clue on how to solve this.

I'm running an older script, version 2.6.4, and I'm deploying the newest version soon, but I'm not able to do it right now.

Can you give me some direction?

Kind regards,

Niels

**Comment by auanasgheps** [comment]
Hi, sorry for the delay, I missed the notification.


I think 2.6.4 is very ancient and was only released on OMV Forum, and I'm sure had a lot of undocumented bugs. Please try the latest version!

**Comment by RHCPNG** [comment]
You can close this issue, it has resolved itself somehow. I still need to upgrade the script, though. It's on my todo.

**Comment by auanasgheps** [comment]
Thanks for providing a feedback!
