### ISSUE TITLE
Docker containers not unpausing

### ISSUE THREAD

**Issue by firasdib** [auanasgheps/snapraid-aio-script#61]
I’ve encountered a few cases where my docker containers are paused, but then not unpaused. Can’t find anything in the logs regarding it.

**Comment by tehniemer** [comment]
Did the script end successfully, or was it aborted? How's your config set up?

**Comment by firasdib** [comment]
@tehniemer they are local.

I have not had this issue since, so I'm not entirely sure what caused it. I will close this issue and reopen if it happens again.
