### ISSUE TITLE
Handle case where snapraid is already running

### ISSUE THREAD

**Issue by firasdib** [auanasgheps/snapraid-aio-script#62]
I run this script every day, but sometimes the execution runs for over 24h, due to large changes to the data. The script should check that snapraid is available before going ahead with pausing and doing all the stuff it does

**Comment by auanasgheps** [comment]
Thank you, I will work on this. The script will stop and alert the user via the configured notification methods.

By the way, are you sure you want your jobs to run for 24h?

**Comment by auanasgheps** [comment]
Implemented in dev branch. Tested and works as expected! Will close this out.
