### ISSUE TITLE
Add option to specify different snapraid-aio config file

### ISSUE THREAD

**Issue by Cartache** [auanasgheps/snapraid-aio-script#65]
HI all,

Thanks for this wondefull all-in-one script which I use with such a pleasure.

Currently, when I encounter a situation where the update count of updated/deleted files is higher than the threshhold, I have to manually run the command to force a sync from the command line on the server.
I would really appreciate the possibility to rexecute a dedicated cron job with a different config file (without deleted/updated files theshhold) after checking the reasons behind the warnings.

To be completely honest I use the [cronicle](https://github.com/jhuckaby/Cronicle) app (that I recommend) to manage all my cron jobs on all my servers. Some jobs are set as "manual". AIO script is a perfect example.

Thank you,
Denis

**Comment by auanasgheps** [comment]
Hello! Thanks for proposing this feauture!

It is certainly doable and I'm working on it. Hopefully I'll provide an update soon

**Comment by auanasgheps** [comment]
I made the changes to the dev branch.

You can now run the script with another config file by specifying the path of the file, such as `snapraid-aio-script.sh script-config2.sh` (if in the same folder)

I will update the documentation soon

**Comment by Cartache** [comment]
Hi,
Sorry for not answering but I didn't receive any notifications.
Il will check and keep you posted.
Thank you again for your help and feedback.

Denis
