### ISSUE TITLE
Add update check to the script

### ISSUE THREAD

**Issue by firasdib** [auanasgheps/snapraid-aio-script#67]
Now that you're actively developing the script, it would be nice if it could check for a new version on startup, and notify us if there is one. That way I don't have to come and check the github page every so often :)

**Comment by auanasgheps** [comment]
That's a good one, but people might non like that the script "calls home" (GitHub), so I'll make sure it that can be disabled.

**Comment by tehniemer** [comment]
You can set up notifications in GitHub to be notified of new releases. 

![Screenshot_20230724-051103.png](https://github.com/auanasgheps/snapraid-aio-script/assets/11021632/1dd0fe16-ff56-4713-976b-68f017dea21b)

**Comment by firasdib** [comment]
@tehniemer That's a good idea! Didn't think of that. It would be nice to get a notification in discord/email about it, but I can see that this is an easier avenue.

I'll let @auanasgheps  decide!

**Comment by auanasgheps** [comment]
I can easily add the notification in the script via email, will do it. Not everyone uses Github regularly.

**Comment by auanasgheps** [comment]
Implemented! I think I've checked so we're close for a release!
