### ISSUE TITLE
Maybe add some custom message when Snapraid job completed?

### ISSUE THREAD

**Issue by dm9tr0** [auanasgheps/snapraid-aio-script#72]
Because honestly when I see something like that I have no idea what should I do - google how to run full scrub or ignore...

`The oldest block was scrubbed 109 days ago, the median 92, the newest 5.  
WARNING! The array is NOT fully synced.  
You have a sync in progress at 99%.  
The 30% of the array is not scrubbed.  
No file has a zero sub-second timestamp.  
No rehash is in progress or needed.  
No error detected.`

**Comment by auanasgheps** [comment]
Can you please add more detail of what you are actually looking for?

These are several messages put together, but they have some degree of context when are shown.

I could add some explanations, but catching all messages it's not an easy task.

**Comment by dm9tr0** [comment]
I executed your script and attached log file, maybe you can explain me what should I do now.
[SnapRAID Script Job started [Thu 05 Oct .log](https://github.com/auanasgheps/snapraid-aio-script/files/12820948/SnapRAID.Script.Job.started.Thu.05.Oct.log)

**Comment by auanasgheps** [comment]
Stop Syncthing before the script execution, some files got changed. If you're running it as container, the feature is built in (stop/pause, then restore)

No files should be moved/changed when sync is running.
