### ISSUE TITLE
Mailx not sending

### ISSUE THREAD

**Issue by Oak-Trees** [auanasgheps/snapraid-aio-script#76]
The script end succesfully and says it send the mail but I never receive a mail on Gmail.

Using Debian, mailx is default installed.

**Comment by auanasgheps** [comment]
Hi there,
Have you configured mailx?
This script does not configure settings of mailx.

The script was born to work with OpenMediaVault (Debian based) which configures `mailx` via its GUI.

**Comment by auanasgheps** [comment]
I'm happy to hear this!
