### ISSUE TITLE
Add ability to specify a config file for snapraid to use 

### ISSUE THREAD

**Issue by ankorite** [auanasgheps/snapraid-aio-script#77]
I am looking to add a second snapraid pool and will need to call the snapraid executable using `snapraid -c /path/to/config cmd` would this be a feature you are interested in adding?

If I feel froggy I might make a PR for it, would you rather it using master or dev for HEAD?

**Comment by auanasgheps** [comment]
Hi, this is already implemented in the dev branch, see #65

**Comment by ankorite** [comment]
Isn't that for separate config files for `snapraid-aio-script` and not for `snapraid` itself? I guess I could make a second config for `snapraid-aio-script` and change `SNAPRAID_BIN="/usr/bin/snapraid"` to `SNAPRAID_BIN="/usr/bin/snapraid -c /path/to/config"` for my second array.

**Comment by auanasgheps** [comment]
Correct! You can reference another config file. This is the entry:

SNAPRAID_CONF="/etc/snapraid.conf"

**Comment by ankorite** [comment]
Thanks! I must have missed it when I was going through the code. If I have any issues I will open a new ticket.
