### ISSUE TITLE
Discord notification not sent upon completion

### ISSUE THREAD

**Issue by Sirver51** [auanasgheps/snapraid-aio-script#78]
The start notification works, but I get no notifications after that. Looking at the script, it seems like it's because the "all jobs done" part of the script only checks if email and custom hooks are defined, and not Discord, Telegram, or Healthchecks, unlike earlier in the script. Changing the following line from:

```bash
  # all jobs done, let's send output to user if configured
  if [ "$EMAIL_ADDRESS" ] || [ -x "$HOOK_NOTIFICATION" ]; then
```

to:

```bash
  # all jobs done, let's send output to user if configured
  if [ "$EMAIL_ADDRESS" ] || [ -x "$HOOK_NOTIFICATION" ] || [ "$HEALTHCHECKS" -eq 1 ] || [ "$TELEGRAM" -eq 1 ] || [ "$DISCORD" -eq 1 ]; then
```

Seems to fix it. Or at least gives the following notification:

![image](https://github.com/auanasgheps/snapraid-aio-script/assets/12772196/f81b8883-6395-4bcd-8723-726d83d6d777)

I dunno if this is worth a pull request since it's just a one line change, but if this is the expected output and nothing is missing, I can submit one if necessary.

**Comment by auanasgheps** [comment]
Hi,
Thanks for this!

To be honest, I was unable to replicate the issue, during my testing I always got the final notification message. But as it works for you, I will implement it.

**Comment by auanasgheps** [comment]
Done, thanks!

**Comment by Sirver51** [comment]
Thanks for adding it! I didn't see that other issue before, which is strange because I did search for it. Should I test with the current dev to get report information? Because the above change only makes the notification work, I don't get a summary or anything.

By the way, I'm surprised you weren't able to replicate it - are you sure you tried it without an email or custom hooks configured? As @jack-mil mentioned[ in the other thread](https://github.com/auanasgheps/snapraid-aio-script/issues/55#issuecomment-1837532157), without the suggested change the function call is only reachable if email and/or a custom hook is configured. At least, if I've read the code correctly.

**Comment by auanasgheps** [comment]
I can't remember, but at this point I can say that I might have not used the same conditions, maybe I forgot to turn off emails.
By the way let me know if you have issues with the current dev branch.
