### ISSUE TITLE
Unused variable SNAPRAID_CONF

### ISSUE THREAD

**Issue by tehniemer** [auanasgheps/snapraid-aio-script#80]
I use OpenMediaVault and am trying out OMV7, in that version the SnapRAID plugin is able to serve muliple arrays so `snapraid.conf` has a unique name for each array. The variable `SNAPRAID_CONF` in the config file is able to be set to something different, but it doesn't seem to be referenced at all in the script.

**Comment by tehniemer** [comment]
I'll look into a fix for this and submit a PR, unless you know how to get it fixed quickly.

**Comment by auanasgheps** [comment]
Thanks for reporting, I still haven't upgraded to OMV7 but surely that's in the plans.  Iwill

**Comment by auanasgheps** [comment]
@tehniemer Is It working fine with OMV7? is there any additional configuration needed?

**Comment by tehniemer** [comment]
It's working as expected.

It would probably be a good idea to add instructions to the config file about changing the default entry for those using OMV7.

**Comment by auanasgheps** [comment]
I will add this information to the README on Github later when I'll try OMV7.

Thanks for letting me know.

**Comment by auanasgheps** [comment]
Working on updating the path to the default OMV7, which will work for users who have one array.

Adding check and notification in case the config file is not found, will also show the file name.

**Comment by tehniemer** [comment]
I responded to your comment about the name of the `.conf` file being unpredictable, even with a single array on OMV7 over at that forum. I also think the script should be configured in a way that will allow it to be adaptable to multiple arrays. I'm guessing this could get complicated, but I'm willing to take on the challenge once I get some free time.

**Comment by auanasgheps** [comment]
I can close this issue: 
- Dev branch now checks if SnapRAID conf file is not found. 
- Script configuration and docs are updated with OMV7 changes

We'll work on improvements in the other issue.
