### ISSUE TITLE
integer expression expected

### ISSUE THREAD

**Issue by auanasgheps** [auanasgheps/snapraid-aio-script#86]
Self reporting an issue from [OMV Forum](https://forum.openmediavault.org/index.php?thread/51525-snapraid-diff-connection-lost/&postID=384750#post384750):

./root/Scripts/snapraid-aio-script.sh: line 791: [: : integer expression expected

Dev branch.

**Comment by auanasgheps** [comment]
Line 791 is part of this, checks if ADD_DELL_RATIO is lower than the threshold, if true produces the extra warning.


```shell
    if [ "$DEL_COUNT" -ge  "$DEL_THRESHOLD" ] && [ "$UPDATE_COUNT" -ge "$UP_THRESHOLD" ] && [ "$DO_SYNC" -eq 0 ]; then
      MSG="Multiple violations - Deleted files ($DEL_COUNT) / ($DEL_THRESHOLD) and changed files ($UPDATE_COUNT) / ($UP_THRESHOLD)"
		if [ "$(echo "$ADD_DEL_RATIO < $ADD_DEL_THRESHOLD" | bc -l)" -eq 1 ]; then
		  MSG="Multiple violations - Deleted files ($DEL_COUNT) / ($DEL_THRESHOLD), add/delete ratio ($ADD_DEL_RATIO) / ($ADD_DEL_THRESHOLD), and changed files ($UPDATE_COUNT) / ($UP_THRESHOLD)"
		fi
```

I have tried to replicate the issue, but the script works correctly:

`[WARNING] Multiple violations - Deleted files (3) / (2), add/delete ratio (.33) / (0.5), and changed files (6) / (5) (SnapRAID on omv-test)`

Please clarify your environment conditions, what are your settings and what the script did show until that point?

**Comment by Br33ce** [comment]
Thanks for creating the issue for me.
I am running `OMV 7 - 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 `
I've attached my settings (renamend to .txt for upload purposes as github does not like .sh)
[script-config.txt](https://github.com/auanasgheps/snapraid-aio-script/files/14574789/script-config.txt).

I've just run the script but could not reproduce the error. I think(!) it was a too many differences error, but did not create a screenshot. 
I will monitor it and report back is all I can offer for now (sorry :-/). 

Just to explain my setup: I've setup tiered caching with mergerfs so I dont need to run the script very often (hence the higher values for scrub / changed files). I could prob. do with a simpler script but like yours, especially the report just too much :)

**Comment by auanasgheps** [comment]
You're not using ADD / DELETE Threshold so I don't know how that error is related to you.

I'll keep testing the script but I'm not sure what I'll get. If nothing comes up I'll close this issue but you can always re-open it.

**Comment by auanasgheps** [comment]
Closing.
