### ISSUE TITLE
Dependencies should be listed in the ReadMe

### ISSUE THREAD

**Issue by tehniemer** [auanasgheps/snapraid-aio-script#87]
I noticed there are more dependencies required in the `dev` version, it would probably be a good idea to list them in the ReadMe somewhere so people understand what will be installed on their systems on the first run of the script.

**Comment by auanasgheps** [comment]
The dependencies are:

- python3-markdown
- curl
- bc
- jq

These are listed in the [dev ReadMe](https://github.com/auanasgheps/snapraid-aio-script/blob/dev/README.md#requirements).

By the way, the `dev` script checks and installs all the dependencies, before was only checking for some.
