### ISSUE TITLE
[question/feature request] Is there a explicit option to "force sync" option?

### ISSUE THREAD

**Issue by rpgdev** [auanasgheps/snapraid-aio-script#89]
I've been getting the "Forced sync is not enabled. **NOT** proceeding with SYNC job" often due to some file operations I've been doing lately, is there a explicit FORCE_SYNC option? The wording of this warning makes it seem as if there was one but as far as I understand it this can be accomplished by way of either the `SYNC_WARN_THRESHOLD`  or `ADD_DEL_THRESHOLD` but sometimes you may just want to force a sync via the script. I saw others were using a different config file with such settings changed for such instances but is there a explicit FORCE_SYNC option that can be used? If not, it'd be great to have one that could also be passed as an cli argument to the script.

**Comment by auanasgheps** [comment]
To achieve a Forced Sync, simply configure:
` SYNC_WARN_THRESHOLD=0`

Which is in fact what I use daily on my server.

I don't understand why you'd like to have an explicit option for it.

**Comment by rpgdev** [comment]
Actually, just re-read all possible values in the config and this will work for me, thanks. I still think a explicit FORCE_SYNC would still be valuable, specially from the command line, then it wouldn't "overload" this option since the wording doesn't suggest that it would be useful for forcing a sync.

**Comment by tehniemer** [comment]
This is explicitly stated in the description for `SYNC_WARN_THRESHOLD`

>Set to 0 to ALWAYS force a sync

**Comment by rpgdev** [comment]
I know, that's the first thing I acknowledged in my comment.

**Comment by tehniemer** [comment]
I guess I just don't see the point of another variable to do the same thing.

**Comment by auanasgheps** [comment]
I will add a little clarification in the config description. 

I know it's easy to miss options: the script has become quite packed of features, but I try my best to document each setting here on GitHub and in the config file.

**Comment by auanasgheps** [comment]
Posting an update here since it may interest you.
I've added a `--force-sync` command argument. You can find it in the `dev ` branch, it is also documented in the readme. I hope it will help for future scenarios!
