### ISSUE TITLE
./snapraid-aio-script.sh: line 567: /usr/bin/snapraid: No such file or directory

### ISSUE THREAD

**Issue by zz0rk** [auanasgheps/snapraid-aio-script#91]
Debian 12
snapraid binary location: /usr/local/bin/snapraid
snapraid-aio-script location: ~/scripts/snapraid-aio-script-v.3.3/snapraid-aio-script.sh

> [WARNING] - Unable to continue with SYNC/SCRUB job(s). Check DIFF job output. (SnapRAID on snapraid)
> 
> SnapRAID Script Job started [Tue Apr 2 06:00:28 AM PDT 2024]
> Running SnapRAID version 12.3
> SnapRAID AIO Script version 3.3
> Using configuration file: ./script-config.sh
> Preprocessing
> 
> SnapRAID is not running, proceeding.
> Checking if all parity and content files are present.
> All parity files found.
> All content files found.
> Processing
> SnapRAID TOUCH [Tue Apr 2 06:00:28 AM PDT 2024]
> 
> Checking for zero sub-second files.
> ./snapraid-aio-script.sh: line 567: /usr/bin/snapraid: No such file or directory
> No zero sub-second timestamp files found.
> TOUCH finished [Tue Apr 2 06:00:28 AM PDT 2024]
> SnapRAID DIFF [Tue Apr 2 06:00:28 AM PDT 2024]
> 
> DIFF finished [Tue Apr 2 06:00:28 AM PDT 2024]
> ERROR - Failed to get one or more count values. Unable to continue.
> Exiting script. [Tue Apr 2 06:00:28 AM PDT 2024]
> 

Thank you.

**Comment by auanasgheps** [comment]
Hi there, 

You need to change the snapraid bin directory.
The script defaults to `/usr/bin/snapraid` but as you stated yours is in `/usr/local/bin/snapraid`

Go to the config file, it's here:
https://github.com/auanasgheps/snapraid-aio-script/blob/ecbaa73b4ebc5654600378cf3593aabe089aa08e/script-config.sh#L219

Save it and run again!

**Comment by zz0rk** [comment]
@auanasgheps  :man_facepalming: Jeez, that was simple. How did I miss that, lol. Thanks!

**Comment by zz0rk** [comment]
[snapraid-aio-script/script-config.sh](https://github.com/auanasgheps/snapraid-aio-script/blob/ecbaa73b4ebc5654600378cf3593aabe089aa08e/script-config.sh#L219)

Line 219 in [ecbaa73](https://github.com/auanasgheps/snapraid-aio-script/commit/ecbaa73b4ebc5654600378cf3593aabe089aa08e)

 SNAPRAID_BIN="/usr/bin/snapraid"

**Comment by auanasgheps** [comment]
Happy to know the problem was fixed! I will add an error message to have a clear output for the next time :)
