### ISSUE TITLE
Always shows newer version is available when curl is not installed.

### ISSUE THREAD

**Issue by DonkeeeyKong** [auanasgheps/snapraid-aio-script#93]
Thanks for the great script. I set it up yesterday (version 3.3). Everything worked well, the e-mail I got contained the following part though:

> /opt/snapraid-aio-script/snapraid-aio-script.sh: Zeile 125: curl: Kommando nicht gefunden.
> A newer version () is available! You can find more information by visiting https://github.com/auanasgheps/snapraid-aio-script/releases

Curl is not installed on my system. Looking into the code, the script seems to check if curl is installed only when Discord, Telegram or Healthcheck notifications are enabled. However, it is always used to check for updates as well, and, if not installed, produces the above output even when running the latest version of the script.

**Comment by auanasgheps** [comment]
I have fixed the issue in dev, pushing the update soon.
