### ISSUE TITLE
Problem with disk spin down

### ISSUE THREAD

**Issue by andreapx** [auanasgheps/snapraid-aio-script#99]
In line 330 there is the command to spin down the disk: `hd-idle -t /dev/"$DRIVE"` but it trows the error `/dev//dev/sda: No such file or directory`.
It seems that `hd-idle` just needs the drive name like `sda`, not the whole path.

**Comment by phidauex** [comment]
Unfortunately spin down doesn’t work with the hd-idle binaries in most default repos, you need to switch to the adelomo version that includes fixes not yet available in the mainline repos. See this section of the documentation to install: https://github.com/auanasgheps/snapraid-aio-script?tab=readme-ov-file#installing-hd-idle-for-automatic-disk-spindown

**Comment by andreapx** [comment]
I've missed that, thanks!

**Comment by auanasgheps** [comment]
Thanks @phidauex for the response!
